### ISSUE TITLE
`AngularUpdate` class is not used in the codebase

### ISSUE THREAD

**Issue by bampakoa** [expertly-simple/angular-evergreen#111]
@duluca during working with the codebase of the extension, I noticed that `angularUpdater.ts` is not used in the code. Is this something that could be removed or deprecated somehow? Thanks!

**Comment by duluca** [comment]
I think we can remove

**Comment by bampakoa** [comment]
We should do it after #101 has been merged so that we do not introduce any conflicts.

**Comment by bampakoa** [comment]
@duluca I have decided to go on with this issue because #101 seems to have been stalled. Could you please review my PR? Thanks!
