### ISSUE TITLE
Run Angular Evergreen won't run when settings exists

### ISSUE THREAD

**Issue by duluca** [expertly-simple/angular-evergreen#39]
if settings exists
```
{
  "ng-evergreen.checkFrequency": "Hourly"
}
```
and you run 'Run Angular Evergreen', the command doesn't run to show up the pop-up message

**Comment by duluca** [comment]
Added project causing the issue
[ng8-app.zip](https://github.com/expertly-simple/angular-evergreen/files/3368832/ng8-app.zip)

**Comment by kentonbmax** [comment]
@duluca I believe this is resolved in the current master branch. If so please close.
