### ISSUE TITLE
v7.x to 8.1.2 - Clean branch continues to throw error

### ISSUE THREAD

**Issue by kentonbmax** [expertly-simple/angular-evergreen#58]
1. performed a pull updating my branch. 
2. Ran run evergreen command. Update - latest. 

Result: I continue to get an error about my branch.
ExpResult: Update runs.

**Comment by duluca** [comment]
Can you provided details on the error message you're getting? And if possible a link to the branch in question

**Comment by kentonbmax** [comment]
I tried this again today. I believe that restarting vsc after a pull request was the trick. Still not ideal. Windows 10.
