### ISSUE TITLE
OnLoad @ windows OS does not seem to run plugin

### ISSUE THREAD

**Issue by kentonbmax** [expertly-simple/angular-evergreen#59]
@angular/core 4.1.3
@angular/cli 1.0.3
OS Windows 10

Result: Nothing happens when loading project. 
ExResult: Modal or evergreen message are shown.

**Comment by duluca** [comment]
Is this a Windows 10 specific issue or an angular cli 1.0 specific issue? I've testing on Windows 10 with CLI v8 that seemed to work

**Comment by kentonbmax** [comment]
Still happens on windows 10. Will try updating a few versions of my cli.

**Comment by kentonbmax** [comment]
fixed in #75
