### ISSUE TITLE
Regular update checks aren't happening reliably

### ISSUE THREAD

**Issue by duluca** [expertly-simple/angular-evergreen#60]
i.e. setting check frequency to Daily doesn't ensure that updates are checked for once a day

Actual behavior: VSCode has to be up an running a day for the check to happen
Expected behavior: Ensure that you check once a day even if the computer was off, sleeping, hibernating

**Comment by kentonbmax** [comment]
The get version logic has several redundancies which are affecting performance. They should be resolved as part of this.

**Comment by kentonbmax** [comment]
#75
