### ISSUE TITLE
I need light and dark svg icons

### ISSUE THREAD

**Issue by kentonbmax** [expertly-simple/angular-evergreen#65]
Checkout MS vscode docker extension, not sure if we can use those?

**Comment by duluca** [comment]
In black and white or any requirements?

**Comment by kentonbmax** [comment]
Please check out the icons in the sample extension i referenced.

**Comment by kentonbmax** [comment]
I need icons for web links like a globe, and for what we want to use for our run commands if angular badge not sufficient.

**Comment by brendoncaulkins** [comment]
Any reason not to just use the free Font Awesome icons?

**Comment by kentonbmax** [comment]
found the internal icon reference.
