### ISSUE TITLE
Remind me later

### ISSUE THREAD

**Issue by duluca** [expertly-simple/angular-evergreen#9]
When update message appears, be able to dismiss the notification for a period or time or until next release

(in one week, in one month, skip release)

**Comment by bjsawyer** [comment]
@duluca I have some questions about this one. Currently we have a `setInterval` used to determine how often the `ng update` command should run in the background. Do you envision having a second `setInterval` once the update message appears, based on whether the user's selected "Remind Me Later" interval?

For the "skip release" option, how granular should this be? Are you imagining this to skip until any new version comes out (major, minor, patch, next, alpha, etc.)?

**Comment by duluca** [comment]
i'd say whatever the current update channel you've selected (latest vs next) when you click on remind me later, we store the current version checked, say 8.0.2 and then when we see an update in the same channel we pop-up reminder again. Whatcha think?

**Comment by bjsawyer** [comment]
Makes sense 👍
