### ISSUE TITLE
ng update --all functionality has been removed

### ISSUE THREAD

**Issue by theoklitosBam7** [expertly-simple/angular-evergreen#94]
## Commands

- Update Angular --all
- Update Angular --all --force
- Update Angular --next --all
- Update Angular --next --all --force

As we read on Angular's [docs](https://angular.io/cli/update) the `--all` option is **Deprecated**. So, when we execute the above commands we take as a result the following message:

`--all functionality has been removed as updating multiple packages at once is not recommended.
To update packages which don’t provide 'ng update' capabilities in your workspace 'package.json' use 'npm update' instead.
Run the package manager update command after updating packages which provide 'ng update' capabilities.`

**Comment by bampakoa** [comment]
Thank you for reporting that @theoklitosBam7 🙏 

@duluca shall we adjust the quick command list accordingly?

**Comment by duluca** [comment]
Yes, we should. We could parse the output of `ng update` and come up with our homegrown `all` option that automatically does it one by one. Thoughts?

**Comment by bampakoa** [comment]
@duluca it looks a good fit for #88. We can read Angular related libraries directly from `package.json` and execute the `ng update` command passing their names as an option. What do you think?

**Comment by duluca** [comment]
@bampakoa sounds good to me.

**Comment by bampakoa** [comment]
@theoklitosBam7 thanks again for reporting this issue. In the latest version, we have removed the `--all` switch 👍
